
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 5;
  public static final int CHAR = 38;
  public static final int POR = 19;
  public static final int FRASE = 46;
  public static final int INT = 37;
  public static final int IMPLICA = 32;
  public static final int FOR = 10;
  public static final int CP = 4;
  public static final int NOT = 25;
  public static final int MENORIGUAL = 23;
  public static final int AND = 28;
  public static final int IGUAL = 14;
  public static final int CASTCHAR = 33;
  public static final int OR = 29;
  public static final int DIV = 18;
  public static final int NUM = 43;
  public static final int CC = 6;
  public static final int IF = 2;
  public static final int MAYORIGUAL = 24;
  public static final int BOOLEAN = 41;
  public static final int EOF = 0;
  public static final int ASIG = 20;
  public static final int EXITS = 31;
  public static final int TRUE = 47;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int DIF = 13;
  public static final int MENOS = 17;
  public static final int MENOR = 22;
  public static final int IDENT = 42;
  public static final int CASTBOOL = 36;
  public static final int MENOSUNARIO = 49;
  public static final int CLL = 27;
  public static final int REAL = 44;
  public static final int MAYOR = 21;
  public static final int CASTINT = 34;
  public static final int ELSE = 7;
  public static final int WHILE = 8;
  public static final int FLOAT = 39;
  public static final int STRING = 40;
  public static final int ALL = 26;
  public static final int FALSE = 48;
  public static final int ASCII = 45;
  public static final int AP = 3;
  public static final int CASTFLOAT = 35;
  public static final int PRINT = 12;
  public static final int LENGTH = 15;
  public static final int DO = 9;
  public static final int PYC = 11;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "AP",
  "CP",
  "AC",
  "CC",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PYC",
  "PRINT",
  "DIF",
  "IGUAL",
  "LENGTH",
  "MAS",
  "MENOS",
  "DIV",
  "POR",
  "ASIG",
  "MAYOR",
  "MENOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "NOT",
  "ALL",
  "CLL",
  "AND",
  "OR",
  "COMA",
  "EXITS",
  "IMPLICA",
  "CASTCHAR",
  "CASTINT",
  "CASTFLOAT",
  "CASTBOOL",
  "INT",
  "CHAR",
  "FLOAT",
  "STRING",
  "BOOLEAN",
  "IDENT",
  "NUM",
  "REAL",
  "ASCII",
  "FRASE",
  "TRUE",
  "FALSE",
  "MENOSUNARIO"
  };
}

